### ISSUE TITLE
Gas tank monitor syntax

### ISSUE THREAD

**Issue by craiggillieson** [jmc5105/gas-tank-monitoring#1]
Apologies up front, I’m a newb. Very much struggling to make this work, any idea what I’m doing wrong? 

```
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - entity: sensor.blah_propane_tank_level
        above: 80
    card:
      type: picture
      image: http://blah/local/full-tank.png
  - type: conditional
    conditions:
      - entity: sensor.blah_propane_tank_level
        above: 65
        below: 80
    card:
      type: picture
      image: http://blah/local/80-percent.png
  - type: conditional
    conditions:
      - entity: sensor.blah_propane_tank_level
        above: 50
        below: 65
    card:
      type: picture
      image: http://blah/local/65-percent.png
  - type: conditional
    conditions:
      - entity: sensor.blah_propane_tank_level
        above: 35
        below: 50
    card:
      type: picture
      image: http://blah/local/50-percent.png
  - type: conditional
    conditions:
      - entity: sensor.blah_propane_tank_level
        above: 15
        below: 35
    card:
      type: picture
      image: http://blah/local/35-percent.png
  - type: conditional
    conditions:
      - entity: sensor.blah_propane_tank_level
        above: 1
        below: 15
    card:
      type: picture
      image: http://blah/local/15-percent.png
  - type: conditional
    conditions:
      - entity: sensor.blah_propane_tank_level
        below: 1
    card:
      type: picture
      image: http://blah/local/empty-tank.png
```
